substitutions:
  _IMG: webstyle
  _REG: reg.seankhliao.com

tags:
  - $SHORT_SHA
  - $COMMIT_SHA

steps:
  - id: login
    name: gcr.io/cloud-builders/kubectl:latest
    entrypoint: bash
    args:
      - -c
      - |
        gcloud secrets versions access latest \
          --secret=docker-registry-creds \
          --format='get(payload.data)' \
          | tr '_-' '/+' \
          | base64 -d > /kaniko/.docker/config.json
    volumes:
      - name: registry-creds
        path: /kaniko/.docker

  - id: build-push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - -c=.
      - -f=Dockerfile
      - -d=$_REG/$_IMG:latest
      - -d=$_REG/$_IMG:$SHORT_SHA
      - --reproducible
      - --single-snapshot
    volumes:
      - name: registry-creds
        path: /kaniko/.docker
