substitutions:
  _IMG: webstyle
tags:
  - $TAG_NAME
  - $SHORT_SHA
  - $COMMIT_SHA
steps:
  - id: login
    name: gcr.io/cloud-builders/docker:latest
    entrypoint: /bin/bash
    args:
      - -c
      - docker login --username=seankhliao --password=$$PASSWORD
    secretEnv:
      - PASSWORD
  - id: build-push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --context=.
      - --dockerfile=./Dockerfile
      - --destination=us.gcr.io/$PROJECT_ID/$_IMG:latest
      - --destination=us.gcr.io/$PROJECT_ID/$_IMG:$TAG_NAME
      - --destination=seankhliao/$_IMG:latest
      - --destination=seankhliao/$_IMG:$TAG_NAME
      - --reproducible
      - --single-snapshot
secrets:
  - kmsKeyName: projects/com-seankhliao/locations/global/keyRings/cloudbuilder/cryptoKeys/default
    secretEnv:
      DOCKERTOKEN: CiQA7y9SxcYS+I4dHTEC3U8ze+e8Bsuu0tAbnkZjoXy0b9NIxIISTQBb0+9rHFSnCtaURoiRmIf1rBia28+NezZRw6FEiF4msK1RO+xiPNKEbwRZPZ2g0fMQfyG+TMVgDrYKBoXYD+Ze4SQjltZq29nF8Vr1
